# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386c3c000c99920011dc676668888a9ce4ca9e8557e625729e0bebb5a211df0e7a219c5201aab3a265376e25110b56d5b47c5f8c090764a05c40a1b494dccd80

test:
  secret_key_base: c24af4b865621b0997f475d73e179841597ba929dbe1b6c0dc54f6dc190b5b79e344a86bd350cda320436a510c8b354684c816d428ee6cb8b3dd75b2f2d2367a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
